# Generated by Django 5.1.1 on 2024-10-13 02:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('activate', models.BooleanField(db_column='activate', default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('modified_at', models.DateTimeField(auto_now=True, db_column='modified_at')),
                ('name', models.CharField(db_column='name', max_length=70)),
                ('age', models.IntegerField(db_column='age')),
                ('rg', models.CharField(db_column='rg', max_length=12)),
                ('cpf', models.CharField(db_column='cpf', max_length=12)),
            ],
            options={
                'abstract': False,
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('activate', models.BooleanField(db_column='activate', default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('modified_at', models.DateTimeField(auto_now=True, db_column='modified_at')),
                ('name', models.CharField(db_column='name', max_length=70)),
                ('registration', models.CharField(db_column='registration', max_length=15)),
            ],
            options={
                'abstract': False,
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('activate', models.BooleanField(db_column='activate', default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('modified_at', models.DateTimeField(auto_now=True, db_column='modified_at')),
                ('description', models.CharField(db_column='description', max_length=100)),
                ('quantity', models.IntegerField(db_column='quantity')),
            ],
            options={
                'abstract': False,
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('activate', models.BooleanField(db_column='activate', default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('modified_at', models.DateTimeField(auto_now=True, db_column='modified_at')),
                ('nrf', models.CharField(db_column='nrf', max_length=255)),
                ('id_client', models.ForeignKey(db_column='id_client', on_delete=django.db.models.deletion.DO_NOTHING, to='teste.client')),
                ('id_employee', models.ForeignKey(db_column='id_employee', on_delete=django.db.models.deletion.DO_NOTHING, to='teste.employee')),
                ('id_product', models.ForeignKey(db_column='id_product', on_delete=django.db.models.deletion.DO_NOTHING, to='teste.product')),
            ],
            options={
                'abstract': False,
                'managed': True,
            },
        ),
    ]
